FROM ubuntu:20.04 as build

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y git libxerces-c-dev libicu-dev libc-dev gcc libglib2.0-dev libffi-dev build-essential libsodium-dev libzstd-dev gdb rsync zip openssh-server cmake libboost-all-dev libdouble-conversion-dev libssl-dev libgoogle-glog-dev gperf -y

RUN mkdir /home/libs && git clone https://github.com/facebook/proxygen.git /home/libs

#next line - fixed fizz build after commits in fizz-main 18 Oct 2022 
RUN echo "Subproject commit 7401af7ee2db6d014730da9c46643926f0901d02" > /home/libs/build/deps/github_hashes/facebookincubator/fizz-rev.txt
RUN cd /home/libs/proxygen/ && ./build.sh --no-tests -j 1 && ./install.sh

#cleanup repo 
RUN cd /home/libs/ && find . -type f \! \( -name '*.h' -or -name '*.cmake' -or -name '*.hpp' -or -name '*.txt' -or -name 'proxygen_*' -or  -name '*.a' -or -name '*so' -or -name '*.so*' \) -delete
RUN cd /home/libs/proxygen/_build && find .  -type f \! \( -wholename './lib*' -or -wholename './bin*'  -or -wholename '*include*' -or -wholename './deps/bin*' -or -wholename './deps/lib*'  \)  -delete

