#FROM proxygen_ubuntu
FROM proxygen_ubuntu_cleaned

ENV DEBIAN_FRONTEND=noninteractive

RUN cd /home/ &&  git clone https://github.com/translate5/translate5-tm-service-source.git 
RUN cd /home/translate5-tm-service-source && git checkout changing_http_lib_proxygen

#add sodium
RUN cp -R /home/translate5-tm-service-source/docker/lib/* /opt/local/lib/ 

RUN cd /home/translate5-tm-service-source && ./build.sh

RUN cp /home/translate5-tm-service-source/_build/t5memory_DEBUG  /root/t5memory_DEBUG

WORKDIR /root

ENTRYPOINT [ "/root/t5memory_DEBUG", "---port=8080", "---alsologtostderr=1", "--v=0" ]
EXPOSE 4040 2222 22 4044 4000

#cleanup
RUN rm -R /home/ 
