FROM ubuntu:20.04 as build

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y git libxerces-c-dev libicu-dev libc-dev gcc libglib2.0-dev libffi-dev build-essential libsodium-dev libzstd-dev gdb rsync zip openssh-server cmake libboost-all-dev libdouble-conversion-dev libssl-dev libgoogle-glog-dev gperf -y

RUN mkdir /home/libs && git clone https://github.com/facebook/proxygen.git /home/libs

#next line - fixed fizz build after commits in fizz-main 18 Oct 2022 
RUN echo "Subproject commit 7401af7ee2db6d014730da9c46643926f0901d02" > /home/libs/build/deps/github_hashes/facebookincubator/fizz-rev.txt
RUN cd /home/libs/proxygen/ && ./build.sh && ./install.sh

#setup libs to use with t5memory
RUN mkdir -p /opt/local/lib/cmake/proxygen/
RUN cp -R /home/libs/proxygen/_build/* /opt/local/ && cp -R /home/libs/proxygen/_build/deps/* /opt/local/ && cp /usr/lib/x86_64-linux-gnu/libsodium.a /opt/local/lib/libsodium.a 

#cleanup 
# RUN rm -R /opt/local/deps && rm -R /home/libs 

